version: '3'
services:
  server:
    build: .
    ports:
      - 80:3000
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=35.199.115.173
      - DATABASE_USER=habla
      - DATABASE_PASSWORD=habla
      - DATABASE_NAME=habla